### ISSUE TITLE
"TypeError: fromhex() argument must be str, not int" messages in debug log 

### ISSUE THREAD

**Issue by walkjivefly** [electrum-altcoin/electrum#30]
With Electrum Crown v0.0.3a (actually anything built after c8d17e0b25e857ad32a67fc494aea52a28149311) the debug log contains periodical batches of messages saying:

```
Traceback (most recent call last):
  File "/var/tmp/.mount_electrSQLoSq/usr/lib/python3.7/site-packages/electrum/ecc.py", line 383, in verify_message_with_address
    addr = pubkey_to_address(txin_type, pubkey_hex, net=net)
  File "/var/tmp/.mount_electrSQLoSq/usr/lib/python3.7/site-packages/electrum/bitcoin.py", line 394, in pubkey_to_address
    return public_key_to_p2pkh(bfh(pubkey), net=net)
  File "/var/tmp/.mount_electrSQLoSq/usr/lib/python3.7/site-packages/electrum/bitcoin.py", line 369, in public_key_to_p2pkh
    return hash160_to_p2pkh(hash_160(public_key), net=net)
  File "/var/tmp/.mount_electrSQLoSq/usr/lib/python3.7/site-packages/electrum/bitcoin.py", line 361, in hash160_to_p2pkh
    return hash160_to_b58_address(h160, net.ADDRTYPE_P2PKH)
  File "/var/tmp/.mount_electrSQLoSq/usr/lib/python3.7/site-packages/electrum/bitcoin.py", line 340, in hash160_to_b58_address
    return override(h160, addrtype)
  File "/var/tmp/.mount_electrSQLoSq/usr/lib/python3.7/site-packages/electrum/networks/crowncoin_mainnet.py", line 155, in hash160_to_b58_address
    s = bfh(addrtype)
TypeError: fromhex() argument must be str, not int
```
They appear to be asynchronous, not related to doing anything in particular in the wallet.

**Comment by ahmedbodi** [comment]
Related to the Update Checker
